# Generated by Django 3.2.9 on 2021-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('target', models.TextField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
